#! /bin/bash

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo ERROR: "$@" FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

# export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
cd "$TESTDIR"
# echo ">> WARNING test-virus-name disabled on 2020-04-09 in ~/AD/sources/acmacs-virus/test/test"
../dist/test-virus-name
../dist/test-passage
